name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: android-actions/setup-android@v3
        with: { api-level: 34, build-tools: "34.0.0" }
      - name: Install Gradle CLI (to create wrapper if missing)
        run: sudo apt-get update -y && sudo apt-get install -y gradle
      - name: Create Gradle wrapper (if absent)
        working-directory: android
        run: |
          if [ ! -f gradlew ]; then
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x gradlew
      - name: Build Debug APK
        working-directory: android
        run: ./gradlew --no-daemon clean assembleDebug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DispatchOne-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
